generator_arch: betavae
loss_reconstruction: mse

factor_names:
  - floor_color
  - wall_color
  - object_color

label_ratio: 0.1

factor_dim: 1
residual_dim: 8

residual_std: 1

train:
  batch_size: 64
  n_epochs: 200

  learning_rate:
    latent: 0.01
    generator: 0.001
#    encoder: 0.001
    min: 0.00001

  loss_weights:
    reconstruction: 1
    entropy: 0.1
    residual_decay: 0.001
